version: "3"

services:
  postgres:
    environment:
      - POSTGRES_USER=metaci
      - POSTGRES_DB=metaci
    image: postgres:10.6
    ports: 
    - "5432:5432"
    restart: always
  redis:
    image: 'redis:5'
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      /bin/bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; \
        sleep 1; /app/start_server.sh'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - config/settings/.env
    volumes:
      - .:/app
