version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      sleep 1
      python /app/manage.py migrate \
      && python /app/manage.py runserver 0.0.0.0:8000 \
      && python /app/manage.py rqscheduler --queue short \
      && python /app/manage.py metaci_rqworker short'
    ports:
      - "8000:8000"
      - "4088:4088"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    env_file:
      - config/settings/.env
    environment:
      - REDIS_URL
  db:
    image: postgres:10.6
    user: postgres
    restart: always
    ports: 
    - "5432:5432"
  redis:
    image: 'redis:5'
    ports:
      - '6379:6379'