<<<<<<< HEAD
version: "3"

services:
  web:
    volumes:
      - .:/app:delegated
      - vscode-server:/root/.vscode-server:cached
      - /var/run/docker.sock:/var/run/docker.sock:cached
    # Override command to prevent container crashing if webpack build exits
    command: sleep infinity

volumes:
  vscode-server: {}
=======
version: "3"

services:
  web:
    volumes:
      - .:/app:delegated
      - vscode-server:/root/.vscode-server:cached
      - /var/run/docker.sock:/var/run/docker.sock:cached
    # Override command to prevent container crashing if webpack build exits
    command: sleep infinity

volumes:
  vscode-server: {}
>>>>>>> f12c8c9c7addb1dc6b3dc20eda086220a3629d50
